// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOhbFDmDk2v525EjPEn3p0MqP69jU0dSI',
    appId: '1:811802718965:web:3bfcd385a1e8c58f6b4bbc',
    messagingSenderId: '811802718965',
    projectId: 'spencer-60175',
    authDomain: 'spencer-60175.firebaseapp.com',
    storageBucket: 'spencer-60175.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3tnENZoLHipifukrcKrz6YVS_VNmUp2E',
    appId: '1:811802718965:android:85b86b50ff4107b36b4bbc',
    messagingSenderId: '811802718965',
    projectId: 'spencer-60175',
    storageBucket: 'spencer-60175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjInxTF2CDE-HxqJj0GOKWx2lhoCUGwIA',
    appId: '1:811802718965:ios:d6a8116f62b45a6a6b4bbc',
    messagingSenderId: '811802718965',
    projectId: 'spencer-60175',
    storageBucket: 'spencer-60175.appspot.com',
    iosBundleId: 'com.example.spencerFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjInxTF2CDE-HxqJj0GOKWx2lhoCUGwIA',
    appId: '1:811802718965:ios:6ee995e7e90221716b4bbc',
    messagingSenderId: '811802718965',
    projectId: 'spencer-60175',
    storageBucket: 'spencer-60175.appspot.com',
    iosBundleId: 'com.example.spencerFrontend.RunnerTests',
  );
}
